Feat/selection topics
dmdeh/job-cracker pull request #10
Opened 2024-12-23 11:24 UTC by dmdeh

## #️⃣ 연관된 이슈

#3 

## ✏️ 작업 내용

- 주제 선택 페이지 구현 및 주제 선택 후 확인 버튼 클릭 시 라우팅

- 전체 선택 후 확인버튼 클릭하면 아래와 같이 긴 주소로 이동됩니다. 주소가 긴 점이 고민입니다.
- `/selection/topics/contents?selected=HTML+%2F+CSS%2CJavaScript%2CTypeScript%2CReact`

- 주제의 데이터 형식을 TOPICS_Frontend, Backend, iOS로 나누는 방식으로 저장했습니다.

<img width="1624" alt="스크린샷 2024-12-23 오후 8 06 38" src="https://github.com/user-attachments/assets/e4235736-5441-4924-b6ca-e8b37aaf2007" />

## 🎸 기타사항

2024-12-23 11:29 UTC, schnee98 commented
이건 #8, #9 머지되면 볼게요.. ㅎ;

2024-12-26 05:55 UTC, schnee98 approved these changes

2024-12-26 05:55 UTC, schnee98 commented on src/app/common/Button/Button.tsx
> +    ...style
style이랑 className이 왜 동시에 필요한가요?

2024-12-26 05:55 UTC, schnee98 commented on src/app/components/DeveloperCard/DeveloperCard.tsx
> +    const topic = title.split(" ")[0];
(사소)
```suggestion
    const [topic] = title.split(" ");
```

2024-12-26 05:55 UTC, schnee98 commented on src/app/selection/topics/page.tsx
> +  const topic = searchParams.get("topic") as TopicKey;
아.. 이렇게 타입을 단언하는 방식은 안좋아요.
런타임에서 string이 TopicKey인 것이 보장되지 않는데 이렇게 단언해버리면 런타임 오류가 생길 가능성이 매우 커요.

getTopic과 isTopic으로 타입 체크를 할 수 있으면 좋겠어요

2024-12-26 05:55 UTC, schnee98 commented on src/app/selection/topics/page.tsx
> +  };
```suggestion
const toggleSelectTopic = (item: string) => {
    if (selected.includes(item)) {
      setSelected(selected.filter((selectedItem) => selectedItem !== item));
      return;
    }

    setSelected([...selected, item]);
  };
```

너무 숏코딩하면 가독성이 안좋아서 보기 헷갈려요

2024-12-26 05:55 UTC, schnee98 commented on src/app/selection/topics/page.tsx
> +  }`;
`clsx`를 써보시는건 어떤가요?

https://nextjs.org/learn/dashboard-app/css-styling#using-the-clsx-library-to-toggle-class-names

2024-12-26 05:55 UTC, schnee98 commented on src/app/selection/topics/page.tsx
> +        {allTopics.map((key) => (
key라는 이름보단 topic이 더 맞는 이름 같네요

2024-12-26 05:55 UTC, schnee98 commented on src/app/selection/topics/page.tsx
> +          className={`${styles.card} ${isAllSelected && styles.selected}`}
> `clsx`를 써보시는건 어떤가요?

+1

2024-12-26 05:55 UTC, schnee98 commented on src/app/selection/topics/page.tsx
> +  const toggleSelectAll = () => setSelected(isAllSelected ? [] : allTopics);
```suggestion
const toggleSelectAll = () => {
    if (isAllSelected) {
      setSelected([]);
    }

    setSelected(allTopics);
  };
```

> 너무 숏코딩하면 가독성이 안좋아서 보기 헷갈려요

+1

2024-12-26 05:56 UTC, schnee98 requested changes
악 잘못 approve 눌렀네요

2024-12-26 05:59 UTC, dmdeh commented on src/app/components/DeveloperCard/DeveloperCard.tsx
> +    const topic = title.split(" ")[0];
와!!!!!!!!!

2024-12-26 06:03 UTC, dmdeh commented on src/app/common/Button/Button.tsx
> +    ...style
styles.button로 공통 스타일 넣어주고 className으로 shadow, transition 같은 따로 추가해주고 싶은 속성 넣어줬는데
이 속성들도 props로 받는게 더 나을까요?

2024-12-26 06:35 UTC, schnee98 commented on src/app/common/Button/Button.tsx
> +    ...style
📝
- 기존 방식에서는 children, onClick, className까지 style attribute에 적용이 되어 hydration error가 생긴다
- CSSProperties를 제외한 prop들을 먼저 해체할당하고 남은 prop (CSSProperties) 들을 해체하여 button#style에 적용한다

2024-12-26 07:25 UTC, schnee98 commented on src/app/utils/className.ts
> +}
이렇게 넣으면 안대여.. css module은 클래스 네임이 충돌되지 않게 동적으로 클래스 네임이 변하기 때문에 하드코딩으로 넣으면 적용이 되지 않습니다

2024-12-26 07:38 UTC, schnee98 approved these changes

2024-12-26 07:44 UTC, merged