주제 상세 선택 페이지 구현
dmdeh/job-cracker pull request #13
Opened 2024-12-27 08:05 UTC by dmdeh

## #️⃣ 연관된 이슈

#4 

## ✏️ 작업 내용
- 주제 상세 선택 페이지 구현 및 주제 선택 후 확인 버튼 클릭 시 `/question` 라우팅 처리
- 주제 선택 페이지와 공통으로 사용되는 카드 컴포넌트 분리, 카드 선택(전체선택) 함수 util 함수로 분리
- 주제 선택 페이지에서 상세 선택 페이지로 라우팅될 때 front, back, ios 확인이 필요해서 url 수정해줬습니다.
  - `/selection/topics/contents?topic=${topic}&selected=${selected.join(",")}`

<img width="50%" alt="스크린샷 2024-12-27 오후 4 50 34" src="https://github.com/user-attachments/assets/2335aff3-e0e0-4c0c-ba38-efa027088790" /><img width="50%" alt="스크린샷 2024-12-27 오후 4 50 31" src="https://github.com/user-attachments/assets/3e38a3d7-a899-49e8-9ad5-822fd0355078" />

- 제네릭 사용해봤습니다..! 재사용성있는 함수로 만들긴 했는데 여기서는 string[]에만 사용돼서 어떤 방식으로 하는게 더 좋을지는 잘 모르겠어요. 그리고 toggleSelectAllProps로 따로 타입 분리해보려고 했는데 사용하는 곳에서 에러가 나서 일단 지금 방식으로 올려뒀습니다. 
수정해볼게요.

```ts
export function toggleSelectAll<T>(
  isAllSelected: boolean,
  setSelected: React.Dispatch<React.SetStateAction<T[]>>,
  topicContents: T[]
) {
  if (isAllSelected) {
    setSelected([]);
  } else {
    setSelected(topicContents);
  }
}
```

- Layout 잡아야할거 같아요. 공통 Layout 스타일 추가해서 스타일 수정 예정입니다.

## 🎸 기타사항
```
'string' 형식의 식을 '{}' 인덱스 형식에 사용할 수 없으므로 요소에 암시적으로 'any' 형식이 있습니다.
  '{}' 형식에서 'string' 형식의 매개 변수가 포함된 인덱스 시그니처를 찾을 수 없습니다. 
```
- selectedTopics에서 타입 에러가 나서 아래처럼 선언해줬는데 어떻게 해줘야하는지 잘 모르겠습니다. 이건 아닌거같다고,, 생각했어요 ㅎㅎ
```ts
const selectedTopics: { [key: string]: string[] } = topic ? TOPIC_MAP[topic] : {};
```

2024-12-27 08:42 UTC, schnee98 requested changes

2024-12-27 08:42 UTC, schnee98 commented on src/app/utils/toggleSelection.ts
> +}
이 함수들은 주제 선택, 세부 주제 선택에서 재사용 되겠지만 유틸 성격의 함수가 아닌것 같아요

https://velog.io/@jjh099/React-utils%EC%99%80-hooks-%EA%B5%AC%EB%B6%84%ED%95%98%EA%B8%B0#utils%EC%9C%A0%ED%8B%B8%EB%A6%AC%ED%8B%B0

> 어디에서든 불러와 사용할 수 있는, 범용적인 로직을 담당하는 곳이라고 할 수 있다.

T라는 타입도 primitive 데이터 타입에만 적용할 수 있을 것 같고 참조형 데이터 (object, array 등) 에는 작동을 잘할 것 같지는 않네요

2024-12-27 08:42 UTC, schnee98 commented on src/app/selection/topics/contents/page.tsx
> +    : {};
getTopic에서 default value을 설정하면 이렇게 삼항 연산자로 구분할 필요가 없을 것 같고 타입 명시도 없어도 될 것 같아요

2024-12-27 08:42 UTC, schnee98 commented on src/app/selection/topics/contents/page.tsx
> +        disabled={selected.length === 0}
isAllSelected는 변수화 하였는데 선택되지 않았는지도 변수로 있으면 보기 더 좋을 것 같아요

2024-12-27 08:42 UTC, schnee98 commented on src/app/selection/topics/contents/page.tsx
> +  const topicContents = contents.map((key) => selectedTopics[key]).flat();
위에 default value를 적용한 후에 topicContents를 어떻게 더 잘 가져올 수 있을지 고민해봐도 좋을 것 같아요

2024-12-27 08:42 UTC, schnee98 commented on src/app/selection/topics/contents/page.tsx
> +"use client";
다른데는 use client를 제거하셨는데 여기서는 적용하신 이유가 있으셨나요?

2024-12-27 13:02 UTC, schnee98 commented on src/app/selection/topics/contents/page.tsx
> +        backgroundColor="var(--color-background-light)"
colors 상수를 만드는 것은 어떠신가요?

+) globals.css에 --foreground, --background 스타일 변수가 있던데 이거는 어디서 정의 되어있나요?

2024-12-27 13:04 UTC, dmdeh commented on src/app/selection/topics/contents/page.tsx
> +"use client";
selected 상태때문에 유지했어요! 선택 상태로 가지고있는거 말고 다른 방법을 못찾았습니다ㅜㅜ

2024-12-27 13:05 UTC, dmdeh commented on src/app/utils/toggleSelection.ts
> +}
공통된 함수라서 분리했는데 다시 생각해볼게요ㅜㅜ

2024-12-28 10:40 UTC, dmdeh commented on src/app/selection/topics/contents/page.tsx
> +        backgroundColor="var(--color-background-light)"
colors 상수가 export const BACKGROUND_LIGTH 이런 형태 말하시는게 맞을까요..?
+ 그 친구들은 기존에 있던 변수들인데 삭제를 못했네요..

2024-12-28 10:43 UTC, dmdeh commented on src/app/selection/topics/contents/page.tsx
> +  const topicContents = contents.map((key) => selectedTopics[key]).flat();
```tsconst isContents = (value: string): value is ContentsKey =>
    value in selectedTopics;

  const contents = searchParams.get("selected")?.split(",") || [];
  const topicContents = contents
    .filter(isContents)
    .map((key) => selectedTopics[key])
    .flat();
`

2024-12-28 14:58 UTC, schnee98 commented on src/app/utils/getTopicContents.ts
> +}
아 이건 저도 회사에서 받았던 리뷰인데요..
reduce + spread operator는 시간 복잡도가 O(n^2)과 같은 안티패턴이라고 하더라구요
그러면 filter + reduce + spread 로서 또다시 수정 전과 같이 array를 세번 순회하게 될 것 같네요.
시간 나시면 [링크](https://www.richsnapp.com/article/2019/06-09-reduce-spread-anti-pattern) 한번 읽어보시길 바랄게요.

```suggestion
function getTopicContents(
  topics: (typeof TOPIC_MAP)[TopicKey],
  selectedContents: string[]
) {
  return Object.entries(topics).reduce<string[]>((acc, [key, value]) => {
    if (selectedContents.includes(key)) {
      acc.push(...value);
    }

    return acc;
  }, []);
}
```

2024-12-29 01:02 UTC, dmdeh commented on src/app/utils/getTopicContents.ts
> +}
넵 감사합니다ㅜㅜ

2024-12-29 06:43 UTC, schnee98 approved these changes

2024-12-29 08:51 UTC, merged