개발자 선택 페이지 구현
dmdeh/job-cracker pull request #9
Opened 2024-12-23 08:05 UTC by dmdeh

## #️⃣ 연관된 이슈

> #2 

## ✏️ 작업 내용

- 개발자 선택 페이지 구현 및 카드 클릭 시 주제 선택 페이지로 라우팅  
- 개발자 선택 후 라우팅 방식을 상태 저장해서 전달할지 쿼리 파라미터로 할지 고민했는데
  새로고침해도 선택사항 유지하고싶어서 쿼리 파라미터로 설정했습니다.

<img width="1624" alt="스크린샷 2024-12-23 오후 4 54 06" src="https://github.com/user-attachments/assets/960a0d1c-0291-4e79-96bd-cca64cafb8c7" />

## 🎸 기타사항
- Next.js의 router.push가 기본적인 인코딩 처리를 해준다. 공백만 처리해주면 돼서 추가하지 않았는데 필요한 경우 encodeURIComponent() 사용해주면 된다.

2024-12-23 11:27 UTC, schnee98 requested changes

2024-12-23 11:27 UTC, schnee98 commented on src/app/components/DeveloperCard/DeveloperCard.module.css
> +  box-shadow: 5px 5px 4px #e5e7eb;
여기만 색상이 하드코딩 되어 있는 이유가 따로 있으실까요?

2024-12-23 11:27 UTC, schnee98 commented on src/app/components/DeveloperCard/DeveloperCard.module.css
> +  background-color: var(--color-cardBackground);
https://github.com/dmdeh/job-cracker/pull/8#discussion_r1895633517
+1

2024-12-23 11:27 UTC, schnee98 commented on src/app/components/DeveloperCard/DeveloperCard.tsx
> +  technologies: string[];
technologies 라는 이름은 어떤 주제라고 알려주기에는 조금 헷갈리는 이름인 것 같아요.
skills 아니면 themes 는 어떠신가요?

2024-12-23 11:27 UTC, schnee98 commented on src/app/page.module.css
> +    transform-origin: 50% 50%;
`text-pop-up-top` 애니메이션이 .title에만 적용될 애니메이션이라면, transform-origin을 .title에 적용하는게 중복을 줄일 수 있을 것 같네욤

2024-12-23 11:27 UTC, schnee98 commented on src/app/components/DeveloperCard/DeveloperCard.module.css
> +  padding: 0.3rem 0.7rem;
이렇게 소숫점 계산을 유발하는 방식의 css적용은 사용자 디바이스나 해상도마다 1px씩 어긋나는 경우가 있어서 차라리 px을 넣는 걸 추천드립니당

2024-12-23 11:28 UTC, schnee98 commented
그리고 #8 을 수정하시고 머지하면 develop -> feat/selection-developer로 merge 부탁드립니다

2024-12-25 01:38 UTC, dmdeh commented on src/app/components/DeveloperCard/DeveloperCard.module.css
> +  box-shadow: 5px 5px 4px #e5e7eb;
웹에서 색상 조정하다가 넣어버렸네요,,ㅎㅎ 팔레트에 저장해두겠습니다

2024-12-25 02:32 UTC, dmdeh commented on src/app/components/DeveloperCard/DeveloperCard.tsx
> +  technologies: string[];
다음 페이지명을 topics로 해서 topics로 수정했습니다! topics도 조금 헷갈리면 페이지명이랑 같이 변경해볼게요

2024-12-25 03:24 UTC, schnee98 requested changes

2024-12-25 03:24 UTC, schnee98 commented on src/app/components/DeveloperCard/DeveloperCard.tsx
> +    <div className={styles.card}>
```suggestion
  const router = useRouter();

  const handleCardClick = (title: string) => {
    router.push(`/selection/topics?topic=${title}`);
  };

  return (
    <div className={styles.card} onClick={() => handleCardClick(title)}>
```

저는 이렇게 핸들러를 넣는게 컴포넌트 역할이 더 명확하게 보인다고 생각해요

2024-12-25 03:24 UTC, schnee98 commented on src/app/selection/developer/page.tsx
> +  return (
```suggestion
import { DeveloperCard } from "@/app/components/DeveloperCard/DeveloperCard";

export default function Developer() {
  return (
```

2024-12-25 03:24 UTC, schnee98 commented on src/app/selection/developer/page.tsx
> +          </div>
```suggestion
          <DeveloperCard key={dev.title} {...dev} />
```

이 div는 의미 없는 것 같아욤

2024-12-25 03:26 UTC, schnee98 commented on src/app/components/DeveloperCard/DeveloperCard.tsx
> +  technologies: string[];
topics두 괜찮네용

2024-12-25 03:30 UTC, schnee98 commented
> 이후의 주제 선택, 상세 주제 선택 시에도 쿼리 파라미터 사용해야할거같은데 상태로 수정하는게 나을지 고민입니다..

쿼리 파라미터로 전달하든 클라이언트 상태로 저장하든 하나로 통일하면 어느 방법이든 괜찮을 것 같네요

2024-12-25 16:48 UTC, schnee98 commented on src/app/constants/topics.ts
> +export const TOPICS_CONTENTS = {
(매우 사소)

```suggestion
export const TOPIC_CONTENTS = {
```

2024-12-26 01:21 UTC, dmdeh commented on src/app/constants/topics.ts
> +export const TOPICS_CONTENTS = {
다음 브랜치에서 TOPICS_FRONTEND, _BACKEND, _IOS 이렇게 데이터 쪼개서 구현해서 변경안하고 리뷰 요청 보냈습니다!

2024-12-26 04:35 UTC, schnee98 approved these changes

2024-12-26 05:28 UTC, merged